/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_dtools_ritglove_NativeGlove */

#ifndef _Included_gnu_dtools_ritglove_NativeGlove
#define _Included_gnu_dtools_ritglove_NativeGlove
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_dtools_ritglove_NativeGlove_LEFT_HANDED
#define gnu_dtools_ritglove_NativeGlove_LEFT_HANDED 0L
#undef gnu_dtools_ritglove_NativeGlove_RIGHT_HANDED
#define gnu_dtools_ritglove_NativeGlove_RIGHT_HANDED 1L
#undef gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_NO_GLOVE
#define gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_NO_GLOVE 0L
#undef gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_7
#define gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_7 1L
#undef gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_7W
#define gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_7W 2L
#undef gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_16
#define gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_16 3L
#undef gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_16W
#define gnu_dtools_ritglove_NativeGlove_GLOVE_TYPE_16W 4L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_FIST
#define gnu_dtools_ritglove_NativeGlove_GESTURE_FIST 0L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_INDEX_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_INDEX_FINGER_POINT 1L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_UP_YOURS
#define gnu_dtools_ritglove_NativeGlove_GESTURE_UP_YOURS 2L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_TWO_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_TWO_FINGER_POINT 3L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_RING_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_RING_FINGER_POINT 4L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_RING_INDEX_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_RING_INDEX_FINGER_POINT 5L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_RING_MIDDLE_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_RING_MIDDLE_FINGER_POINT 6L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_THREE_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_THREE_FINGER_POINT 7L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_LITTLE_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_LITTLE_FINGER_POINT 8L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_HOWZIT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_HOWZIT 9L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_LITTLE_MIDDLE_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_LITTLE_MIDDLE_FINGER_POINT 10L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_NOT_RING_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_NOT_RING_FINGER_POINT 11L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_LITTLE_RING_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_LITTLE_RING_FINGER_POINT 12L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_NOT_UP_YOURS
#define gnu_dtools_ritglove_NativeGlove_GESTURE_NOT_UP_YOURS 13L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_NOT_INDEX_FINGER_POINT
#define gnu_dtools_ritglove_NativeGlove_GESTURE_NOT_INDEX_FINGER_POINT 14L
#undef gnu_dtools_ritglove_NativeGlove_GESTURE_FLAT_HAND
#define gnu_dtools_ritglove_NativeGlove_GESTURE_FLAT_HAND 15L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_FLEXURE 0L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_SECOND_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_SECOND_FLEXURE 1L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_ABDUCTION
#define gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_ABDUCTION 2L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_INDEX_FINGER_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_INDEX_FINGER_FLEXURE 3L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_INDEX_FINGER_SECOND_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_INDEX_FINGER_SECOND_FLEXURE 4L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_INDEX_FINGER_ABDUCTION
#define gnu_dtools_ritglove_NativeGlove_SENSOR_INDEX_FINGER_ABDUCTION 5L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_MIDDLE_FINGER_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_MIDDLE_FINGER_FLEXURE 6L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_MIDDLE_FINGER_SECOND_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_MIDDLE_FINGER_SECOND_FLEXURE 7L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_MIDDLE_FINGER_ABDUCTION
#define gnu_dtools_ritglove_NativeGlove_SENSOR_MIDDLE_FINGER_ABDUCTION 8L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_RING_FINGER_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_RING_FINGER_FLEXURE 9L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_RING_FINGER_SECOND_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_RING_FINGER_SECOND_FLEXURE 10L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_RING_FINGER_ABDUCTION
#define gnu_dtools_ritglove_NativeGlove_SENSOR_RING_FINGER_ABDUCTION 11L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_LITTLE_FINGER_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_LITTLE_FINGER_FLEXURE 12L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_LITTLE_FINGER_SECOND_FLEXURE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_LITTLE_FINGER_SECOND_FLEXURE 13L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_TRANSLATION
#define gnu_dtools_ritglove_NativeGlove_SENSOR_THUMB_TRANSLATION 14L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_WRIST_TRANSLATION
#define gnu_dtools_ritglove_NativeGlove_SENSOR_WRIST_TRANSLATION 15L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_PITCH_ANGLE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_PITCH_ANGLE 16L
#undef gnu_dtools_ritglove_NativeGlove_SENSOR_ROLL_ANGLE
#define gnu_dtools_ritglove_NativeGlove_SENSOR_ROLL_ANGLE 17L
/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    initGloveArray
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_initGloveArray
  (JNIEnv *, jclass);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    nativeClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_nativeClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getNumberOfSensors
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getNumberOfSensors
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getGloveType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getGloveType
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getHandedness
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getHandedness
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getRawSensorData
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_gnu_dtools_ritglove_NativeGlove_getRawSensorData__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getRawSensorData
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_gnu_dtools_ritglove_NativeGlove_getRawSensorData__
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    setRawSensorData
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_setRawSensorData__IS
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    setRawSensorData
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_setRawSensorData___3S
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getScaledSensorData
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_gnu_dtools_ritglove_NativeGlove_getScaledSensorData__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getScaledSensorData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_gnu_dtools_ritglove_NativeGlove_getScaledSensorData__
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getNumberOfGestures
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getNumberOfGestures
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getGesture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getGesture
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getCalibration
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_gnu_dtools_ritglove_NativeGlove_getCalibration
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    setCalibration
 * Signature: (ISS)V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_setCalibration
  (JNIEnv *, jobject, jint, jshort, jshort);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    resetCalibration
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_resetCalibration
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getSensorMaximums
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_gnu_dtools_ritglove_NativeGlove_getSensorMaximums
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getSensorMaximum
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_gnu_dtools_ritglove_NativeGlove_getSensorMaximum
  (JNIEnv *, jobject, jint);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    setSensorMaximums
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_setSensorMaximums
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    setSensorMaximum
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_setSensorMaximum
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getThreshold
 * Signature: ([F[F)I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getThreshold___3F_3F
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getThreshold
 * Signature: (IFF)I
 */
JNIEXPORT jint JNICALL Java_gnu_dtools_ritglove_NativeGlove_getThreshold__IFF
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    setThresholdAll
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_gnu_dtools_ritglove_NativeGlove_setThresholdAll
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getGloveInfo
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_gnu_dtools_ritglove_NativeGlove_getGloveInfo
  (JNIEnv *, jobject);

/*
 * Class:     gnu_dtools_ritglove_NativeGlove
 * Method:    getDriverInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gnu_dtools_ritglove_NativeGlove_getDriverInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
